### ISSUE TITLE
Does it support angular2

### ISSUE THREAD

**Issue by nandamashokkumar** [toddmotto/angular-1-5-components-app#25]
@toddmotto, Hi toddmotto i tried it for angular2 projects, i got an issues 

info:    running processor: readFilesProcessor
error:   Error: No file reader found for /home/lantronix/Desktop/git-xing/doc-generator/angular2-signin/src/app/app-routing.module.ts
    at matchFileReader (/home/lantronix/Desktop/git-xing/doc-generator/angular2-signin/node_modules/dgeni-packages/base/processors/read-files.js:130:25)
    at /home/lantronix/Desktop/git-xing/doc-generator/angular2-signin/node_modules/dgeni-packages/base/processors/read-files.js:66:99
error:   Error processing docs:  Error: No file reader found for /home/lantronix/Desktop/git-xing/doc-generator/angular2-signin/src/app/app-routing.module.ts
    at matchFileReader (/home/lantronix/Desktop/git-xing/doc-generator/angular2-signin/node_modules/dgeni-packages/base/processors/read-files.js:130:25)
    at /home/lantronix/Desktop/git-xing/doc-generator/angular2-signin/node_modules/dgeni-packages/base/processors/read-files.js:66:99
[08:52:46] 'dgeni' errored after 315 ms
[08:52:46] Error: No file reader found for /home/lantronix/Desktop/git-xing/doc-generator/angular2-signin/src/app/app-routing.module.ts
    at matchFileReader (/home/lantronix/Desktop/git-xing/doc-generator/angular2-signin/node_modules/dgeni-packages/base/processors/read-files.js:130:25)
    at /home/lantronix/Desktop/git-xing/doc-generator/angular2-signin/node_modules/dgeni-packages/base/processors/read-files.js:66:99
lantr

Can u please fix it

**Comment by toddmotto** [comment]
This is for 1.x, not v2 and above - it's not compatible.
